port 1194
proto udp
dev tun
ca /etc/openvpn/pki/ca.crt
cert /etc/openvpn/pki/issued/server.crt
key /etc/openvpn/pki/private/server.key
dh /etc/openvpn/pki/dh.pem
auth SHA256
tls-auth /etc/openvpn/ta.key 0
topology subnet
server 192.168.255.0 255.255.255.0
ifconfig-pool-persist ipp.txt
push "route 192.168.1.0 255.255.255.0"
push "route 192.168.1.207 255.255.255.255"
push "dhcp-option DNS 192.168.1.207"
push "dhcp-option DOMAIN matkoland"
keepalive 10 120
cipher AES-256-CBC
user nobody
group nogroup
persist-key
persist-tun
status openvpn-status.log
verb 5
explicit-exit-notify 1